#!/usr/bin/env bats
# shellcheck disable=SC2016,SC2030,SC2031

setup() {
  export ENV_RECOVERY_REAL_LN ENV_RECOVERY_REAL_MV ENV_RECOVERY_REAL_RM
  ENV_RECOVERY_REAL_LN="$(type -P ln)"
  ENV_RECOVERY_REAL_MV="$(type -P mv)"
  ENV_RECOVERY_REAL_RM="$(type -P rm)"
  load test_helper
  export ENV_RECOVERY_ROOT="$HOME/.config/zdx/env-profiles"
  export ENV_RECOVERY_LOG="$HOME/recovery.calls"
  export ENV_RECOVERY_MODE=normal
  mkdir -p "$ENV_RECOVERY_ROOT"
  chmod 700 "$HOME/.config" "$HOME/.config/zdx" "$ENV_RECOVERY_ROOT"
  printf '# zdx-environment-profile-v1\nZDX_RECOVERY_VALUE=original\n' \
    > "$ENV_RECOVERY_ROOT/reviewed.env"
  printf '# zdx-environment-profile-v1\nZDX_RECOVERY_VALUE=other\n' \
    > "$ENV_RECOVERY_ROOT/unrelated.env"
  printf 'ZDX_RECOVERY_VALUE=original\n' > "$HOME/.env"
  printf 'ZDX_RECOVERY_VALUE=updated\n' > "$HOME/.env.example"
  chmod 600 "$ENV_RECOVERY_ROOT"/*.env "$HOME/.env" "$HOME/.env.example"
  : > "$ENV_RECOVERY_LOG"

  export ENV_RECOVERY_SETUP="$HOME/recovery-setup.zsh"
  cat > "$ENV_RECOVERY_SETUP" <<'EOF'
source "$ZSH_CUSTOM/functions/env-menu.zsh"
unfunction command
cd "$HOME" || return
zmodload zsh/stat
zstat() {
  builtin zstat "$@" || return
  [[ "$1" == -LH && "$3" == -- ]] || return 0
  local inspected_file="$4" state_name="$2"
  local -A real_state=("${(@kvP)state_name}")
  # Rename changes ctime independently of content. Make the difference exact,
  # without sleeps or relying on the filesystem clock's resolution.
  case "$inspected_file" in
    "$ENV_RECOVERY_ROOT/reviewed.env"|"$HOME/.env")
      real_state[ctime]=100
      ;;
    */.zdx-env-write.*/original|*/.zdx-env-delete.*/profile.env)
      real_state[ctime]=200
      ;;
    *) return 0 ;;
  esac
  set -A "$state_name" "${(@kv)real_state}"
}
EOF
  cat > "$TEST_MOCK_BIN/ln" <<'EOF'
#!/usr/bin/env zsh
print -r -- "ln:$*" >> "$ENV_RECOVERY_LOG"
case "$ENV_RECOVERY_MODE" in
  publication-failure) exit 47 ;;
  changed-original)
    print -r -- '# concurrent edit' >> "${1:h}/original"
    exit 47
    ;;
esac
exec "$ENV_RECOVERY_REAL_LN" "$@"
EOF
  cat > "$TEST_MOCK_BIN/mv" <<'EOF'
#!/usr/bin/env zsh
print -r -- "mv:$*" >> "$ENV_RECOVERY_LOG"
"$ENV_RECOVERY_REAL_MV" "$@" || exit
if [[ "$ENV_RECOVERY_MODE" == changed-after-move \
  && "$2" == */.zdx-env-write.*/original ]]; then
  print -r -- '# concurrent edit' >> "$2"
fi
EOF
  cat > "$TEST_MOCK_BIN/rm" <<'EOF'
#!/usr/bin/env zsh
if [[ "$ENV_RECOVERY_MODE" == deletion-failure \
  && "$*" == */.zdx-env-delete.*/profile.env ]]; then
  print -r -- "rm:failed:$*" >> "$ENV_RECOVERY_LOG"
  exit 47
fi
exec "$ENV_RECOVERY_REAL_RM" "$@"
EOF
  chmod +x "$TEST_MOCK_BIN/ln" "$TEST_MOCK_BIN/mv" "$TEST_MOCK_BIN/rm"
}

teardown() {
  export PATH="${PATH#"$TEST_MOCK_BIN:"}"
  cleanup_sandbox
}

@test "env recovery: profile overwrite accepts the ctime change from its own rename" {
  run run_zsh '
    source "$ENV_RECOVERY_SETUP"
    export ZDX_RECOVERY_VALUE=updated
    env-profile-save reviewed ZDX_RECOVERY_VALUE --overwrite --yes
  '

  [ "$status" -eq 0 ]
  [ "$(cat "$ENV_RECOVERY_ROOT/reviewed.env")" = \
    $'# zdx-environment-profile-v1\nZDX_RECOVERY_VALUE=updated' ]
  [ "$(cat "$ENV_RECOVERY_ROOT/unrelated.env")" = \
    $'# zdx-environment-profile-v1\nZDX_RECOVERY_VALUE=other' ]
  [ "$(find "$ENV_RECOVERY_ROOT" -name '.zdx-env-*' | wc -l)" -eq 0 ]
}

@test "env recovery: profile deletion accepts its own rename without touching another profile" {
  run run_zsh 'source "$ENV_RECOVERY_SETUP"; env-profile-delete reviewed --yes'

  [ "$status" -eq 0 ]
  [ ! -e "$ENV_RECOVERY_ROOT/reviewed.env" ]
  [ -f "$ENV_RECOVERY_ROOT/unrelated.env" ]
  [ "$(find "$ENV_RECOVERY_ROOT" -name '.zdx-env-*' | wc -l)" -eq 0 ]
}

@test "env recovery: dotenv overwrite uses the same validated rename transaction" {
  run run_zsh '
    source "$ENV_RECOVERY_SETUP"
    env-create --template .env.example --output .env --overwrite --yes <<< ""
  '

  [ "$status" -eq 0 ]
  [ "$(cat "$HOME/.env")" = \
    $'# Generated by zdx env-create\nZDX_RECOVERY_VALUE=updated' ]
  [ "$(find "$HOME" -name '.zdx-env-write.*' | wc -l)" -eq 0 ]
}

@test "env recovery: publication failure restores the unchanged original after quarantine" {
  export ENV_RECOVERY_MODE=publication-failure
  run run_zsh '
    source "$ENV_RECOVERY_SETUP"
    export ZDX_RECOVERY_VALUE=updated
    env-profile-save reviewed ZDX_RECOVERY_VALUE --overwrite --yes
  '

  [ "$status" -eq 1 ]
  [ "$(cat "$ENV_RECOVERY_ROOT/reviewed.env")" = \
    $'# zdx-environment-profile-v1\nZDX_RECOVERY_VALUE=original' ]
  [ "$(find "$ENV_RECOVERY_ROOT" -name '.zdx-env-*' | wc -l)" -eq 0 ]
  [[ "$output" != *'Saved private'* ]]
}

@test "env recovery: a changed quarantined original is retained instead of restored or deleted" {
  export ENV_RECOVERY_MODE=changed-original
  run run_zsh '
    source "$ENV_RECOVERY_SETUP"
    export ZDX_RECOVERY_VALUE=updated
    env-profile-save reviewed ZDX_RECOVERY_VALUE --overwrite --yes
  '

  [ "$status" -eq 1 ]
  [ ! -e "$ENV_RECOVERY_ROOT/reviewed.env" ]
  local recovered
  recovered="$(find "$ENV_RECOVERY_ROOT" -path '*/.zdx-env-write.*/original' -type f)"
  [ -n "$recovered" ]
  [ "$(cat "$recovered")" = \
    $'# zdx-environment-profile-v1\nZDX_RECOVERY_VALUE=original\n# concurrent edit' ]
  [[ "$output" == *'Recovery data was retained at:'* ]]
}

@test "env recovery: content changes during quarantine never qualify as an expected ctime change" {
  export ENV_RECOVERY_MODE=changed-after-move
  run run_zsh '
    source "$ENV_RECOVERY_SETUP"
    export ZDX_RECOVERY_VALUE=updated
    env-profile-save reviewed ZDX_RECOVERY_VALUE --overwrite --yes
  '

  [ "$status" -eq 1 ]
  [ ! -e "$ENV_RECOVERY_ROOT/reviewed.env" ]
  [[ "$output" == *'quarantined output did not match'* ]]
  [[ "$output" == *'Recovery data was retained at:'* ]]
  run grep -q '^ln:' "$ENV_RECOVERY_LOG"
  [ "$status" -eq 1 ]
}

@test "env recovery: failed deletion retains the exact quarantined profile and reports recovery" {
  export ENV_RECOVERY_MODE=deletion-failure
  run run_zsh 'source "$ENV_RECOVERY_SETUP"; env-profile-delete reviewed --yes'

  [ "$status" -eq 1 ]
  [ ! -e "$ENV_RECOVERY_ROOT/reviewed.env" ]
  local recovered
  recovered="$(find "$ENV_RECOVERY_ROOT" -path '*/.zdx-env-delete.*/profile.env' -type f)"
  [ -n "$recovered" ]
  [ "$(cat "$recovered")" = \
    $'# zdx-environment-profile-v1\nZDX_RECOVERY_VALUE=original' ]
  [[ "$output" == *'Profile recovery data was retained at:'* ]]
  [[ "$output" != *'Deleted environment profile'* ]]
}

@test "env recovery: created dotenv values round trip as literal data including leading quotes" {
  run run_zsh '
    source "$ENV_RECOVERY_SETUP"
    typeset -a reviewed_values=(
      "\"quoted\""
      "\"unclosed"
      "'"'"'single'"'"'"
      "'"'"'unclosed"
      "\"mixed'"'"'quotes"
      "literal\\path\$HOME#suffix"
      ""
    )
    typeset -i audit_index=1
    for audit_index in {1..7}; do
      print -r -- "ZDX_LITERAL_${audit_index}=default"
    done > "$HOME/literal.env.example"
    chmod 600 "$HOME/literal.env.example"
    print -rl -- "${reviewed_values[@]}" > "$HOME/literal.responses"
    # An empty prompt response retains an empty template default.
    print -r -- "ZDX_LITERAL_7=" >> "$HOME/empty.env.example"
    chmod 600 "$HOME/empty.env.example"
    env-create --template literal.env.example --output literal.env --yes \
      < "$HOME/literal.responses" || return
    env-switch literal.env --yes || return
    for audit_index in {1..6}; do
      typeset audit_key="ZDX_LITERAL_${audit_index}"
      [[ "${(P)audit_key}" == "${reviewed_values[audit_index]}" ]] || return 91
    done
    env-create --template empty.env.example --output empty.env --yes <<< "" || return
    env-switch empty.env --yes || return
    [[ "$ZDX_LITERAL_7" == "" ]] || return 92
  '

  [ "$status" -eq 0 ]
  [[ "$output" != *'literal\path$HOME#suffix'* ]]
  [[ "$output" != *'"mixed'* ]]
}

@test "env recovery: multiline creation remains an explicit refusal without partial publication" {
  cat > "$HOME/multiline.env.example" <<'EOF'
ZDX_MULTILINE="first
second"
EOF
  chmod 600 "$HOME/multiline.env.example"
  run run_zsh '
    source "$ENV_RECOVERY_SETUP"
    env-create --template multiline.env.example --output multiline.env --yes <<< ""
  '

  [ "$status" -eq 1 ]
  [ ! -e "$HOME/multiline.env" ]
  [[ "$output" == *'unsupported controls'* ]]
}

@test "env recovery: edge whitespace in a template remains a refusal before publication" {
  local padded_value
  for padded_value in '  token  ' '  "quoted"  '; do
    printf "ZDX_EDGE='%s'\n" "$padded_value" > "$HOME/edge.env.example"
    chmod 600 "$HOME/edge.env.example"
    run run_zsh '
      source "$ENV_RECOVERY_SETUP"
      env-create --template edge.env.example --output edge.env --yes <<< ""
    '

    [ "$status" -eq 1 ]
    [ ! -e "$HOME/edge.env" ]
    [[ "$output" == *'unsupported controls'* ]]
    [[ "$output" != *'token'* ]]
    [[ "$output" != *'quoted'* ]]
  done
}
