#!/usr/bin/env bats

# sys-wsl: the read-only WSL configuration review. Every host fact comes from a
# fixture tree below the sandbox and from mocked Windows interop programs, so
# the review runs the same on Linux, WSL, and macOS hosts.

setup() {
  load test_helper

  export WSL_ROOT="$TEST_TEMP_DIR/wsl-root"
  export DRIVE_ROOT="$TEST_TEMP_DIR/mnt"
  export PROFILE_DIR="$DRIVE_ROOT/c/Users/Jane"
  mkdir -p "$WSL_ROOT/etc/systemd/system/multi-user.target.wants" \
    "$WSL_ROOT/proc/net" "$WSL_ROOT/proc/1" \
    "$WSL_ROOT/sys/class/net/eth0" "$WSL_ROOT/sys/class/net/lo" \
    "$PROFILE_DIR"
  printf 'systemd\n' > "$WSL_ROOT/proc/1/comm"
  printf '%s\n' \
    $'Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT' \
    $'eth0\t00000000\t0120A8C0\t0003\t0\t0\t0\t00000000\t0\t0\t0' \
    $'eth0\t0020A8C0\t00000000\t0001\t0\t0\t0\t00F0FFFF\t0\t0\t0' \
    > "$WSL_ROOT/proc/net/route"
  printf '1392\n' > "$WSL_ROOT/sys/class/net/eth0/mtu"
  printf '65536\n' > "$WSL_ROOT/sys/class/net/lo/mtu"
  printf '%s\n' \
    '# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:' \
    'nameserver 10.255.255.254' > "$WSL_ROOT/etc/resolv.conf"

  # Windows interop mocks record every call; tests never reach real Windows.
  cat > "$TEST_MOCK_BIN/cmd.exe" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "$TEST_TEMP_DIR/cmd.calls"
[[ "${MOCK_CMD_SLEEP:-0}" == 0 ]] || sleep "$MOCK_CMD_SLEEP"
[[ "$*" == "/c echo %USERPROFILE%" ]] || exit 97
printf 'C:\\Users\\Jane\r\n'
EOF
  cat > "$TEST_MOCK_BIN/wslvar" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "$TEST_TEMP_DIR/wslvar.calls"
[[ -n "${MOCK_WSLVAR_PROFILE:-}" ]] || exit 1
printf '%s\r\n' "$MOCK_WSLVAR_PROFILE"
EOF
  cat > "$TEST_MOCK_BIN/wslpath" <<'EOF'
#!/usr/bin/env bash
[[ "${MOCK_WSLPATH_FAIL:-0}" == 0 ]] || exit 1
[[ "$1" == -u && "$2" == [A-Za-z]:\\* ]] || exit 97
windows_path="${2//\\//}"
drive="${windows_path:0:1}"
printf '%s/%s%s\n' "$DRIVE_ROOT" "${drive,,}" "${windows_path:2}"
EOF
  cat > "$TEST_MOCK_BIN/uname" <<'EOF'
#!/usr/bin/env bash
case "${1:-}" in
  -r) echo "6.6.87.2-microsoft-standard-WSL2" ;;
  -m) echo "x86_64" ;;
  *) echo "Linux" ;;
esac
EOF
  chmod +x "$TEST_MOCK_BIN/cmd.exe" "$TEST_MOCK_BIN/wslvar" \
    "$TEST_MOCK_BIN/wslpath" "$TEST_MOCK_BIN/uname"
}

teardown() {
  cleanup_sandbox
}

# Zsh code that pins a WSL host to the fixture tree.
# shellcheck disable=SC2016  # Zsh expands this code, not Bash.
WSL_PREAMBLE='
  export WSL_DISTRO_NAME=Ubuntu-24.04
  _sys_capabilities_refresh() {
    _SYS_CAPABILITIES=(
      os linux environment wsl architecture x86_64
      package_manager apt os_updates_backend unavailable
      service_manager systemd process_backend procps ports_backend ss
      privilege sudo snapd unavailable wsl_interop available
    )
    _SYS_CAPABILITIES_READY=1
  }
  _sys_wsl_config_root() { REPLY="$WSL_ROOT"; }
  _sys_wsl_drive_root() { REPLY="$DRIVE_ROOT"; }
  _sys_wsl_interop_available() { [[ "${MOCK_INTEROP:-1}" == 1 ]]; }
  _sys_wsl_diag_os_name() { print -r -- "Ubuntu 24.04 LTS"; }
'

run_wsl() {
  run run_zsh "$WSL_PREAMBLE
$1"
}

require_jq() {
  command -v jq >/dev/null || skip "jq is not installed"
}

# The configuration with one instance of every finding: malformed lines, a
# metadata-less automount, a boot MTU pin that is not in effect, a WireGuard
# tunnel next to MTU 1500, disabled systemd with enabled units, and a CRLF
# .wslconfig with a byte-order mark. An explicit appendWindowsPath is only a
# fact.
write_findings_fixture() {
  printf '%s\n' \
    '# WSL configuration' \
    '[automount]' \
    'enabled = true' \
    'options = "uid=1000,gid=1000"' \
    '' \
    '[boot]' \
    'systemd=false' \
    'command = /usr/sbin/ip link set dev eth0 mtu 1392' \
    '' \
    '[network]' \
    'generateResolvConf = true' \
    'hostname = devbox' \
    '' \
    '[interop]' \
    'appendWindowsPath = TRUE' \
    '' \
    '[gpu]' \
    'enabled = true' \
    '' \
    'this line is broken' \
    '[bad section' \
    'key=value' > "$WSL_ROOT/etc/wsl.conf"
  printf 'init\n' > "$WSL_ROOT/proc/1/comm"
  printf '1500\n' > "$WSL_ROOT/sys/class/net/eth0/mtu"
  mkdir -p "$WSL_ROOT/sys/class/net/wg0"
  printf 'DEVTYPE=wireguard\nINTERFACE=wg0\n' > "$WSL_ROOT/sys/class/net/wg0/uevent"
  printf '1420\n' > "$WSL_ROOT/sys/class/net/wg0/mtu"
  : > "$WSL_ROOT/etc/systemd/system/multi-user.target.wants/docker.service"
  : > "$WSL_ROOT/etc/systemd/system/multi-user.target.wants/ssh.service"
  printf '\xef\xbb\xbf[wsl2]\r\nmemory=8GB\r\nprocessors=4\r\nnetworkingMode=mirrored\r\ndnsTunneling=true\r\nkernelCommandLine = quiet\r\n[experimental]\r\nautoMemoryReclaim=gradual\r\nsparseVhd=yes\r\n' \
    > "$PROFILE_DIR/.wslconfig"
}

# A configuration without findings.
write_clean_fixture() {
  printf '%s\n' \
    '[automount]' \
    'options = "metadata,umask=22,fmask=11"' \
    '[boot]' \
    'systemd = true' \
    'command = ip link set eth0 mtu 1392' \
    '[interop]' \
    'appendWindowsPath = false' > "$WSL_ROOT/etc/wsl.conf"
  printf '[wsl2]\nmemory = 8GB\n' > "$PROFILE_DIR/.wslconfig"
}

@test "sys wsl: help, invalid arguments, and repeated flags" {
  run_wsl 'sys-wsl --help >"$HOME/out" 2>"$HOME/err"'
  [ "$status" -eq 0 ]
  [ ! -s "$HOME/out" ]
  grep -Fq 'Usage: sys-wsl [--json] [-h|--help]' "$HOME/err"

  local arguments
  for arguments in '--bogus' 'extra' '--json --json' '--json --help' '--help --json'; do
    run_wsl "sys-wsl $arguments >\"\$HOME/out\" 2>/dev/null"
    [ "$status" -eq 2 ]
    [ ! -s "$HOME/out" ]
  done
}

@test "sys wsl: native Linux and macOS report that the review does not apply" {
  require_jq
  local platform
  for platform in 'os linux environment native' 'os darwin environment native'; do
    run run_zsh "
      _sys_capabilities_refresh() {
        _SYS_CAPABILITIES=(
          $platform architecture x86_64 package_manager apt
          os_updates_backend unavailable service_manager unavailable
          process_backend procps ports_backend ss privilege sudo
          snapd unavailable wsl_interop unavailable
        )
        _SYS_CAPABILITIES_READY=1
      }
      _sys_wsl_read_config_text() { print -r -- read >> \"\$HOME/touched\"; return 1; }
      sys-wsl >\"\$HOME/text.out\" 2>\"\$HOME/text.err\"
      print -r -- \"text:\$?\"
      sys-wsl --json >\"\$HOME/json.out\" 2>\"\$HOME/json.err\"
      print -r -- \"json:\$?\"
    "
    [ "$status" -eq 0 ]
    [ "$output" = $'text:1\njson:1' ]
    [ ! -s "$HOME/text.out" ]
    [ "$(cat "$HOME/text.err")" = "✘ sys-wsl is not applicable on this host: not a WSL host." ]
    [ "$(wc -l < "$HOME/json.out")" -eq 1 ]
    jq -e '(keys_unsorted == ["schema", "applicable", "reason"])
      and .schema == "zdx.sys-wsl.v1" and .applicable == false
      and .reason == "not a WSL host"' "$HOME/json.out"
    [ ! -e "$HOME/touched" ]
  done
}

@test "sys wsl: the review reports every finding on stderr only" {
  write_findings_fixture
  run_wsl 'NO_COLOR=1 sys-wsl >"$HOME/out" 2>"$HOME/err"'

  [ "$status" -eq 0 ]
  [ ! -s "$HOME/out" ]
  local err="$HOME/err"
  grep -Fxq '════ WSL Configuration Review ════' "$err"
  grep -Eq '^  Generation: +WSL2$' "$err"
  grep -Eq '^  Kernel: +6\.6\.87\.2-microsoft-standard-WSL2$' "$err"
  grep -Eq '^  Distribution: +Ubuntu-24\.04$' "$err"
  grep -Eq '^  PID 1: +init$' "$err"
  grep -Eq '^  \[automount\] options +line 4 +uid=1000,gid=1000$' "$err"
  grep -Eq '^  \[automount\] root +default +/mnt/$' "$err"
  grep -Eq '^  \[user\] default +not set +–$' "$err"
  grep -Eq '^  \[gpu\] enabled +line 18 +true$' "$err"
  grep -Fq 'Listed as written and not reviewed: [gpu] enabled.' "$err"
  grep -Fq "Line 20: malformed (no '=' separator)" "$err"
  grep -Fq 'Line 21: malformed (invalid section header)' "$err"
  grep -Fq 'Line 22: malformed (setting under an invalid section header)' "$err"
  grep -Eq '^  Default route: +eth0$' "$err"
  grep -Eq '^  Interface MTU: +1500$' "$err"
  grep -Eq '^  Boot MTU pin: +eth0 → 1392 \(\[boot\] command\)$' "$err"
  grep -Eq '^  resolv\.conf: +generated by WSL$' "$err"
  grep -Eq '^  Networking mode: +mirrored \(\.wslconfig\)$' "$err"
  grep -Eq '^  Tunnels: +wg0 \(wireguard, MTU 1420\)$' "$err"
  grep -Eq "^  Profile: +$DRIVE_ROOT/c/Users/Jane\$" "$err"
  grep -Eq '^  \[wsl2\] memory +line 2 +8GB$' "$err"
  grep -Eq '^  \[wsl2\] processors +line 3 +4$' "$err"
  grep -Eq '^  \[wsl2\] networkingMode +line 4 +mirrored$' "$err"
  grep -Fq "Line 9: malformed ([experimental] sparseVhd expects true or false)" "$err"
  grep -Fq '1. Shut WSL down from Windows: wsl.exe --shutdown' "$err"
  grep -Fq -- "-eq 'Ubuntu-24.04'" "$err"
  grep -Fq 'compact vdisk' "$err"

  grep -Fxq '⚠ /etc/wsl.conf has 3 malformed lines: 20, 21, 22.' "$err"
  grep -Fxq '⚠ Windows drives are mounted without DrvFs metadata, so the File, Python, and Developer suites refuse projects on them.' "$err"
  grep -Fq 'Add metadata to the [automount] options on line 4 of /etc/wsl.conf' "$err"
  grep -Eq '^  \[interop\] appendWindowsPath +line 15 +true$' "$err"
  ! grep -Fq 'appendWindowsPath is enabled' "$err" || false
  grep -Fxq '⚠ The [boot] command pins eth0 to MTU 1392, but eth0 reports MTU 1500.' "$err"
  grep -Fxq '⚠ eth0 uses MTU 1500 next to 1 tunnel interface (wg0 wireguard); a lower path MTU can stall HTTPS after the TCP connect.' "$err"
  grep -Fxq '⚠ systemd is not running (PID 1 is init); 2 enabled service units cannot start: docker.service, ssh.service.' "$err"
  grep -Fxq '⚠ .wslconfig has 1 malformed line: 9.' "$err"
  grep -Fxq '⚠ WSL review: 6 findings — review the output above.' "$err"
  ! grep -Fq 'No memory limit' "$err" || false
  ! grep -Fq '(s)' "$err" || false
}

@test "sys wsl: --json prints one document with typed facts and findings" {
  require_jq
  write_findings_fixture
  run_wsl 'sys-wsl --json >"$HOME/out" 2>"$HOME/err"'

  [ "$status" -eq 0 ]
  [ ! -s "$HOME/err" ]
  [ "$(wc -l < "$HOME/out")" -eq 1 ]
  ! grep -q $'\033' "$HOME/out" || false
  jq -e --arg profile "$PROFILE_DIR" '
    (keys_unsorted[0] == "schema")
    and .schema == "zdx.sys-wsl.v1" and .applicable == true
    and .host == {generation: "WSL2",
      kernel: "6.6.87.2-microsoft-standard-WSL2",
      distribution: "Ubuntu-24.04", os: "Ubuntu 24.04 LTS", pid1: "init",
      systemd_pid1: false,
      enabled_service_units: ["docker.service", "ssh.service"]}
    and .wsl_conf.path == "/etc/wsl.conf" and .wsl_conf.state == "present"
    and .wsl_conf.reason == null
    and .wsl_conf.settings.automount == {enabled: true, root: null,
      options: "uid=1000,gid=1000", metadata: false}
    and .wsl_conf.settings.boot == {systemd: false,
      command: "/usr/sbin/ip link set dev eth0 mtu 1392"}
    and .wsl_conf.settings.network == {generate_resolv_conf: true,
      generate_hosts: null, hostname: "devbox"}
    and .wsl_conf.settings.interop == {enabled: null, append_windows_path: true}
    and .wsl_conf.settings.user == {default: null}
    and .wsl_conf.withheld_keys == []
    and .wsl_conf.other_keys == [{line: 18, section: "gpu", key: "enabled",
      value: "true", withheld: false}]
    and .wsl_conf.malformed_lines == [
      {line: 20, reason: "no '"'"'='"'"' separator"},
      {line: 21, reason: "invalid section header"},
      {line: 22, reason: "setting under an invalid section header"}]
    and .network == {default_interface: "eth0", default_interface_mtu: 1500,
      boot_mtu_pin: {interface: "eth0", mtu: 1392, current_mtu: 1500},
      resolv_conf: "generated", networking_mode: "mirrored",
      networking_mode_source: "wslconfig",
      tunnel_interfaces: [{name: "wg0", kind: "wireguard", mtu: 1420}]}
    and .windows.profile_path == $profile and .windows.reason == null
    and .windows.wslconfig.path == ($profile + "/.wslconfig")
    and .windows.wslconfig.state == "present"
    and .windows.wslconfig.settings.wsl2 == {memory: "8GB", processors: 4,
      swap: null, networking_mode: "mirrored", dns_tunneling: true,
      auto_proxy: null, firewall: null, sparse_vhd: null}
    and .windows.wslconfig.settings.experimental == {
      auto_memory_reclaim: "gradual", sparse_vhd: null}
    and .windows.wslconfig.other_keys == [{line: 6, section: "wsl2",
      key: "kernelCommandLine", value: "quiet", withheld: false}]
    and .windows.wslconfig.malformed_lines == [{line: 9,
      reason: "[experimental] sparseVhd expects true or false"}]
    and .disk.vhdx_size_bytes == null
    and (.disk.compaction_steps | length) == 4
    and ([.findings[].id] == ["wsl-conf-malformed", "automount-metadata",
      "boot-mtu-mismatch", "tunnel-mtu", "systemd-disabled",
      "wslconfig-malformed"])
    and all(.findings[]; (.message | type) == "string"
      and (.remedy | type) == "string")
  ' "$HOME/out"
}

@test "sys wsl: a clean configuration has no findings" {
  require_jq
  write_clean_fixture
  run_wsl '
    NO_COLOR=1 sys-wsl >"$HOME/out" 2>"$HOME/err" || exit 1
    sys-wsl --json >"$HOME/json" 2>/dev/null
  '

  [ "$status" -eq 0 ]
  [ ! -s "$HOME/out" ]
  [ "$(tail -n 1 "$HOME/err")" = "✔ WSL review: no findings." ]
  ! grep -q '^⚠' "$HOME/err" || false
  jq -e '.findings == [] and .wsl_conf.settings.automount.metadata == true
    and .network.boot_mtu_pin == {interface: "eth0", mtu: 1392,
      current_mtu: 1392}
    and .network.networking_mode == "nat"
    and .network.networking_mode_source == "default"
    and .host.systemd_pid1 == true' "$HOME/json"
}

@test "sys wsl: hostile configuration values are data and never execute" {
  require_jq
  printf '[boot]\ncommand = $(touch %s) `touch %s`; ip link set dev eth0 mtu 1400\n[user]\ndefault = ${HOME:?}$(touch %s)\n' \
    "$HOME/pwned-1" "$HOME/pwned-2" "$HOME/pwned-3" > "$WSL_ROOT/etc/wsl.conf"
  printf '[wsl2]\nmemory = $(touch %s)\nswap = `touch %s`\n' \
    "$HOME/pwned-4" "$HOME/pwned-5" > "$PROFILE_DIR/.wslconfig"

  run_wsl '
    NO_COLOR=1 sys-wsl >/dev/null 2>"$HOME/err" || exit 1
    sys-wsl --json >"$HOME/json" 2>/dev/null
  '

  [ "$status" -eq 0 ]
  local marker
  for marker in 1 2 3 4 5; do
    [ ! -e "$HOME/pwned-$marker" ]
  done
  grep -Fq "\$(touch $HOME/pwned-1)" "$HOME/err"
  grep -Fq "\${HOME:?}\$(touch $HOME/pwned-3)" "$HOME/err"
  grep -Eq '^  Boot MTU pin: +eth0 → 1400 ' "$HOME/err"
  jq -e --arg home "$HOME" '
    .wsl_conf.settings.boot.command
      == "$(touch \($home)/pwned-1) `touch \($home)/pwned-2`; ip link set dev eth0 mtu 1400"
    and .wsl_conf.settings.user.default == "${HOME:?}$(touch \($home)/pwned-3)"
    and .windows.wslconfig.settings.wsl2.memory == "$(touch \($home)/pwned-4)"
    and .network.boot_mtu_pin.mtu == 1400' "$HOME/json"
  for marker in 1 2 3 4 5; do
    [ ! -e "$HOME/pwned-$marker" ]
  done
}

@test "sys wsl: a value that may hold a credential is withheld" {
  require_jq
  printf '[boot]\ncommand = mount -t cifs -o username=jane,password=hunter2 //srv/share /srv\n[gpu]\nnote = token=abc123\n' \
    > "$WSL_ROOT/etc/wsl.conf"

  run_wsl '
    NO_COLOR=1 sys-wsl >/dev/null 2>"$HOME/err" || exit 1
    sys-wsl --json >"$HOME/json" 2>/dev/null
  '

  [ "$status" -eq 0 ]
  grep -Eq '^  \[boot\] command +line 2 +\[withheld: may contain a credential\]$' "$HOME/err"
  ! grep -Fq 'hunter2' "$HOME/err" "$HOME/json" || false
  ! grep -Fq 'abc123' "$HOME/err" "$HOME/json" || false
  jq -e '.wsl_conf.settings.boot.command == null
    and .wsl_conf.withheld_keys == ["[boot] command"]
    and .wsl_conf.other_keys == [{line: 4, section: "gpu", key: "note",
      value: null, withheld: true}]' "$HOME/json"
}

@test "sys wsl: the INI parser numbers lines and names malformed ones" {
  # shellcheck disable=SC2016  # Zsh expands this code, not Bash.
  run run_zsh '
    local text=$'"'"'top = 1\n; comment\n  # indented comment\n[ ok ]\nkey = "quoted value"\nnoequals\n=novalue\nbad key = 1\n[bad\nafter = 1\n[good]\nempty =\nctl = a\tb\n\tspaced\t=\tvalue  \n'"'"'
    _sys_wsl_diag_ini_records "$text"
  '

  [ "$status" -eq 0 ]
  local expected
  expected=$'malformed\t1\tsetting outside a section'
  expected+=$'\nsetting\t5\tok\tkey\tquoted value'
  expected+=$'\nmalformed\t6\tno \'=\' separator'
  expected+=$'\nmalformed\t7\tinvalid key'
  expected+=$'\nmalformed\t8\tinvalid key'
  expected+=$'\nmalformed\t9\tinvalid section header'
  expected+=$'\nmalformed\t10\tsetting under an invalid section header'
  expected+=$'\nsetting\t12\tgood\tempty\t'
  expected+=$'\nmalformed\t13\tcontrol character in value'
  expected+=$'\nsetting\t14\tgood\tspaced\tvalue'
  [ "$output" = "$expected" ]
}

@test "sys wsl: unreadable configuration files are reported, never parsed" {
  require_jq
  make_sized_file "$WSL_ROOT/etc/wsl.conf" 70000
  printf '\xff\xfe[\x00w\x00s\x00l\x002\x00]\x00' > "$PROFILE_DIR/.wslconfig"

  run_wsl 'sys-wsl --json >"$HOME/json" 2>/dev/null'

  [ "$status" -eq 0 ]
  jq -e '.wsl_conf.state == "unreadable"
    and .wsl_conf.reason == "larger than 65536 bytes"
    and .wsl_conf.settings.automount.metadata == null
    and .windows.wslconfig.state == "unreadable"
    and .windows.wslconfig.reason == "not UTF-8 text (it contains NUL bytes)"
    and ([.findings[].id] == ["wsl-conf-unreadable", "wslconfig-unreadable"])' \
    "$HOME/json"
}

@test "sys wsl: disabled interop skips Windows settings without calling Windows" {
  require_jq
  write_clean_fixture
  export MOCK_INTEROP=0

  run_wsl '
    NO_COLOR=1 sys-wsl >/dev/null 2>"$HOME/err" || exit 1
    sys-wsl --json >"$HOME/json" 2>/dev/null
  '

  [ "$status" -eq 0 ]
  [ ! -e "$TEST_TEMP_DIR/cmd.calls" ]
  [ ! -e "$TEST_TEMP_DIR/wslvar.calls" ]
  grep -Eq '^  Profile: +unavailable \(Windows interop is unavailable\)$' "$HOME/err"
  grep -Eq '^  Networking mode: +unknown \(\.wslconfig not read\)$' "$HOME/err"
  jq -e '.windows == {profile_path: null,
      reason: "Windows interop is unavailable",
      wslconfig: {path: null, state: "unavailable", reason: null,
        settings: .windows.wslconfig.settings, withheld_keys: [],
        other_keys: [], malformed_lines: []}}
    and .windows.wslconfig.settings.wsl2.memory == null
    and .network.networking_mode == null
    and .network.networking_mode_source == null
    and .findings == []' "$HOME/json"
}

@test "sys wsl: a slow cmd.exe is bounded by the interop deadline" {
  require_jq
  export MOCK_CMD_SLEEP=30
  local started=$SECONDS

  run_wsl '
    _sys_wsl_interop_deadline() { REPLY=1; }
    sys-wsl --json >"$HOME/json" 2>/dev/null
  '

  [ "$status" -eq 0 ]
  (( SECONDS - started < 20 ))
  grep -Fxq '/c echo %USERPROFILE%' "$TEST_TEMP_DIR/cmd.calls"
  jq -e '.windows.profile_path == null
    and .windows.reason == "the Windows user profile could not be resolved"
    and .windows.wslconfig.state == "unavailable"' "$HOME/json"
}

@test "sys wsl: wslvar is preferred and the drive root converts without wslpath" {
  require_jq
  export MOCK_WSLVAR_PROFILE='C:\Users\Jane'
  run_wsl 'sys-wsl --json >"$HOME/json" 2>/dev/null'

  [ "$status" -eq 0 ]
  grep -Fxq 'USERPROFILE' "$TEST_TEMP_DIR/wslvar.calls"
  [ ! -e "$TEST_TEMP_DIR/cmd.calls" ]
  jq -e --arg profile "$PROFILE_DIR" \
    '.windows.profile_path == $profile and .windows.wslconfig.state == "absent"
      and ([.findings[].id] | index("no-memory-limit") != null)' "$HOME/json"

  # A relocated automount root moves the profile when wslpath cannot answer.
  export MOCK_WSLPATH_FAIL=1
  printf '[automount]\nroot = %s/drives/\n' "$TEST_TEMP_DIR" > "$WSL_ROOT/etc/wsl.conf"
  run_wsl 'sys-wsl --json >"$HOME/json" 2>/dev/null'

  [ "$status" -eq 0 ]
  jq -e --arg profile "$TEST_TEMP_DIR/drives/c/Users/Jane" \
    '.windows.profile_path == $profile' "$HOME/json"
}

@test "sys wsl: the MTU hint names vpn-mtu-probe only when the shell knows it" {
  require_jq
  write_findings_fixture
  # The VPN suite defines vpn-mtu-probe when it is loaded; remove it first so
  # the "without" case does not depend on which suites the harness loaded.
  run_wsl 'unfunction vpn-mtu-probe 2>/dev/null
    (( ${+_comps} )) && unset "_comps[vpn-mtu-probe]"
    sys-wsl --json >"$HOME/without" 2>/dev/null
    vpn-mtu-probe() { return 0; }
    sys-wsl --json >"$HOME/with" 2>/dev/null'

  [ "$status" -eq 0 ]
  jq -e '[.findings[] | select(.id == "tunnel-mtu") | .remedy]
    | length == 1 and (.[0] | contains("vpn-mtu-probe") | not)
    and (.[0] | contains("command = /usr/sbin/ip link set dev eth0 mtu <value>"))' \
    "$HOME/without"
  jq -e '[.findings[] | select(.id == "tunnel-mtu") | .remedy]
    | .[0] | startswith("Measure the path MTU with vpn-menu vpn-mtu-probe")' \
    "$HOME/with"
}

@test "sys wsl: systemd enabled but not running is reported" {
  require_jq
  printf '[boot]\nsystemd=true\n' > "$WSL_ROOT/etc/wsl.conf"
  printf 'init\n' > "$WSL_ROOT/proc/1/comm"
  : > "$WSL_ROOT/etc/systemd/system/multi-user.target.wants/cron.service"

  run_wsl 'sys-wsl --json >"$HOME/json" 2>/dev/null'

  [ "$status" -eq 0 ]
  jq -e '[.findings[] | select(.id == "systemd-not-running") | .message]
    == ["[boot] systemd = true, but PID 1 is init; 1 enabled service unit cannot start: cron.service."]' \
    "$HOME/json"
}

@test "sys wsl: --json without jq fails before any probe" {
  run_wsl '
    functions[_sys_test_tool_program]=$functions[_sys_tool_program]
    _sys_tool_program() {
      [[ "$1" == jq ]] && return 1
      _sys_test_tool_program "$@"
    }
    _sys_wsl_review_collect() { print -r -- collected >> "$HOME/touched"; }
    sys-wsl --json >"$HOME/out" 2>"$HOME/err"
  '

  [ "$status" -eq 1 ]
  [ ! -s "$HOME/out" ]
  [ ! -e "$HOME/touched" ]
  grep -Fq -- '--json requires jq' "$HOME/err"
}

@test "sys wsl: the menu marks the review unavailable outside WSL" {
  run run_zsh '
    _SYS_CAPABILITIES=(os linux environment native)
    _SYS_CAPABILITIES_READY=1
    _sys_menu_entry "Review WSL Configuration" sys-wsl "Review WSL."
    _SYS_CAPABILITIES[environment]=wsl
    _sys_menu_entry "Review WSL Configuration" sys-wsl "Review WSL."
  '

  [ "$status" -eq 0 ]
  [ "${lines[0]}" = "  ○ Review WSL Configuration (unavailable: WSL)|sys-wsl|Review WSL." ]
  [ "${lines[1]}" = "  Review WSL Configuration|sys-wsl|Review WSL." ]
}

@test "sys wsl: sys-info and sys-wsl complete --json" {
  run env COMPLETION_FILE="$TEST_SUITE_ROOT/completions/_sys-menu" \
    zsh -f -c '
      capture_specs() {
        local -a words=("$@")
        local -i CURRENT=${#words[@]}
        _arguments() {
          if [[ "${1:-}" == "-C" ]]; then
            words=("${words[@]:1}")
            (( CURRENT-- ))
            state="arguments"
            return 0
          fi
          print -rl -- "$@"
        }
        _describe() { return 0; }
        _message() { print -r -- "MESSAGE:${(j: :)@}"; }
        source "$COMPLETION_FILE"
      }
      local spec
      for spec in "sys-wsl" "sys-info" "sys-menu sys-wsl"; do
        capture_specs ${=spec} "" | grep -Fq -- "--json[Print one JSON document on stdout]" \
          || { print -r -- "missing --json for $spec"; return 1; }
      done
      capture_specs sys-health "" | grep -Fq -- "--json" && return 2
      return 0
    '

  if [ "$status" -ne 0 ]; then
    echo "$output" >&2
  fi
  [ "$status" -eq 0 ]
}
